### ISSUE TITLE
Migrate to Vite

### ISSUE THREAD

**Issue by ad1992** [ad1992/cryptmoji#4]
Currently, we are using create-react-app for build process, for better maintainability and developer experience, lets move to [vite](https://vite.dev/)

Here is why 👇🏻 
* Build time of Vite is significantly faster than CRA 
* Hot Module Replacement(HMR) is faster in Vite as compared to CRA
* Unlike CRA, Vite doesn’t enforce strict path rules, allowing you to import files from outside the src folder
* CRA is no longer maintained and not recommended in official React docs
* Vite has an awesome community

**Comment by SumirSeth** [comment]
Can you add a little more context for interested devs, thank you!

**Comment by ad1992** [comment]
> Can you add a little more context for interested devs, thank you!

Updated the description. Hope its clear now. For further questions, you can post here if any.

**Comment by SumirSeth** [comment]
Will definitely go over the repo now. Why do you want to use vite btw?

**Comment by ad1992** [comment]
> Will definitely go over the repo now. Why do you want to use vite btw?

Added the reasoning in the desc as well :)

**Comment by SumirSeth** [comment]
Hey @ad1992 , i've made the necessary changes and added a PR ( #5 ). Please assign the issue to me and review the PR.

**Comment by ad1992** [comment]
closed via #5
